# Web Usage

## Library

In [3]:
import pandas as pd

## Web Usage

### Filter request html

In [4]:
df = pd.read_csv("webusage.csv")

print("=== Info Dataset ===")
df.info()
print("\n=== Data yang digunakan ===")
df

=== Info Dataset ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132258 entries, 0 to 132257
Data columns (total 9 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Remote host                       132258 non-null  object
 1   Remote logname                    132258 non-null  object
 2   Remote user                       132258 non-null  object
 3   Request time                      132258 non-null  object
 4   Request method                    132258 non-null  object
 5   Request URI                       132258 non-null  object
 6   Request Protocol                  132258 non-null  object
 7   Status                            132258 non-null  int64
 8   Size of response (incl. headers)  132258 non-null  int64
dtypes: int64(2), object(7)
memory usage: 9.1+ MB

=== Data yang digunakan ===

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers)
0,65.55.147.227,-,-,2009-10-15T02:00:24Z,GET,/index.html,HTTP/1.1,200,21878
1,65.55.86.34,-,-,2009-10-15T02:00:58Z,GET,/index.html,HTTP/1.1,200,1416
2,148.188.55.88,-,-,2009-10-15T02:01:41Z,GET,/faq.html,HTTP/1.1,200,10946
3,72.30.57.238,-,-,2009-10-15T02:01:59Z,GET,/contribute.txt,HTTP/1.0,200,39943
4,66.249.139.233,-,-,2009-10-15T02:02:09Z,GET,/faq.html,HTTP/1.1,200,17247
...,...,...,...,...,...,...,...,...,...
132253,66.249.196.230,-,-,2009-10-22T01:58:21Z,GET,/contribute.txt,HTTP/1.1,200,16569
132254,66.249.41.85,-,-,2009-10-22T01:58:22Z,GET,/contribute.txt,HTTP/1.1,200,380
132255,65.55.236.245,-,-,2009-10-22T01:59:33Z,GET,/index.html,HTTP/1.1,200,6695
132256,65.55.198.69,-,-,2009-10-22T01:59:34Z,GET,/contribute.txt,HTTP/1.1,200,47672
132257,65.55.75.208,-,-,2009-10-22T01:59:36Z,GET,/contribute.txt,HTTP/1.1,200,6265

In [5]:
if 'Request URI' not in df.columns:
    raise KeyError("Kolom 'Request URI' tidak ditemukan. Cek nama kolom pada df.columns")

# Filter URL yang mengandung '.html'
html_df = df[df['Request URI'].str.contains(r'\.html', case=False, na=False)]

print("\n=== 10 Request URI yang Mengandung .html ===")
print(html_df['Request URI'].head(10))

# Hitung total baris hasil filter
print("\nJumlah total URI yang mengandung .html:", len(html_df))

=== 10 Request URI yang Mengandung .html ===
0     /index.html
1     /index.html
2       /faq.html
4       /faq.html
5     /index.html
8     /index.html
9     /index.html
10      /faq.html
11    /index.html
12      /faq.html
Name: Request URI, dtype: object

Jumlah total URI yang mengandung .html: 79176

In [6]:
# Simpan hasil ke file baru
html_df.to_csv("filtered_html_requests.csv", index=False)
print("\n✅ File hasil filter disimpan sebagai 'filtered_html_requests.csv'")

✅ File hasil filter disimpan sebagai 'filtered_html_requests.csv'

### Filter status mengambil nilai yg 200

In [7]:
df = pd.read_csv("filtered_html_requests.csv")

print("=== Info Dataset ===")
df.info()
print("\n=== Data yang digunakan ===")
df

=== Info Dataset ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79176 entries, 0 to 79175
Data columns (total 9 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Remote host                       79176 non-null  object
 1   Remote logname                    79176 non-null  object
 2   Remote user                       79176 non-null  object
 3   Request time                      79176 non-null  object
 4   Request method                    79176 non-null  object
 5   Request URI                       79176 non-null  object
 6   Request Protocol                  79176 non-null  object
 7   Status                            79176 non-null  int64
 8   Size of response (incl. headers)  79176 non-null  int64
dtypes: int64(2), object(7)
memory usage: 5.4+ MB

=== Data yang digunakan ===

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers)
0,65.55.147.227,-,-,2009-10-15T02:00:24Z,GET,/index.html,HTTP/1.1,200,21878
1,65.55.86.34,-,-,2009-10-15T02:00:58Z,GET,/index.html,HTTP/1.1,200,1416
2,148.188.55.88,-,-,2009-10-15T02:01:41Z,GET,/faq.html,HTTP/1.1,200,10946
3,66.249.139.233,-,-,2009-10-15T02:02:09Z,GET,/faq.html,HTTP/1.1,200,17247
4,72.30.50.248,-,-,2009-10-15T02:02:13Z,GET,/index.html,HTTP/1.0,200,7883
...,...,...,...,...,...,...,...,...,...
79171,65.55.251.17,-,-,2009-10-22T01:57:24Z,GET,/index.html,HTTP/1.1,200,12300
79172,67.195.151.244,-,-,2009-10-22T01:57:57Z,GET,/index.html,HTTP/1.0,200,19828
79173,65.55.178.30,-,-,2009-10-22T01:58:02Z,GET,/index.html,HTTP/1.1,200,95655
79174,67.195.176.248,-,-,2009-10-22T01:58:07Z,GET,/faq.html,HTTP/1.0,200,35002
79175,65.55.236.245,-,-,2009-10-22T01:59:33Z,GET,/index.html,HTTP/1.1,200,6695

In [8]:
if 'Status' not in df.columns:
    raise KeyError("Kolom 'Status' tidak ditemukan. Cek nama kolom pada df.columns")

# Filter hanya yang Status = 200
status_200 = df[df['Status'] == 200]

print("\n=== 10 Baris dengan Status = 200 ===")
print(status_200.head(10))

# Hitung jumlah total baris hasil filter
print("\nJumlah total baris dengan Status = 200:", len(status_200))

=== 10 Baris dengan Status = 200 ===
      Remote host Remote logname Remote user          Request time  \
0   65.55.147.227              -           -  2009-10-15T02:00:24Z
1     65.55.86.34              -           -  2009-10-15T02:00:58Z
2   148.188.55.88              -           -  2009-10-15T02:01:41Z
3  66.249.139.233              -           -  2009-10-15T02:02:09Z
4    72.30.50.248              -           -  2009-10-15T02:02:13Z
5     65.55.80.97              -           -  2009-10-15T02:02:51Z
6    65.55.161.41              -           -  2009-10-15T02:02:54Z
7   65.55.119.204              -           -  2009-10-15T02:02:55Z
8    65.55.58.168              -           -  2009-10-15T02:02:56Z
9     65.55.35.29              -           -  2009-10-15T02:02:55Z

  Request method  Request URI Request Protocol  Status  \
0            GET  /index.html         HTTP/1.1     200
1            GET  /index.html         HTTP/1.1     200
2            GET    /faq.html         HTTP/1.1     200
3            GET    /faq.html         HTTP/1.1     200
4            GET  /index.html         HTTP/1.0     200
5            GET  /index.html         HTTP/1.1     200
6            GET  /index.html         HTTP/1.1     200
7            GET    /faq.html         HTTP/1.1     200
8            GET  /index.html         HTTP/1.1     200
9            GET    /faq.html         HTTP/1.1     200

   Size of response (incl. headers)
0                             21878
1                              1416
2                             10946
3                             17247
4                              7883
5                              1416
6                             37122
7                             64380
8                              1202
9                            269198

Jumlah total baris dengan Status = 200: 75718

In [9]:
# Simpan hasil ke file baru
status_200.to_csv("filtered_status_200.csv", index=False)
print("\n✅ File hasil filter disimpan sebagai 'filtered_status_200.csv'")

✅ File hasil filter disimpan sebagai 'filtered_status_200.csv'

### Filter request method mengambil yang GET

In [10]:
df = pd.read_csv("filtered_status_200.csv")

print("=== Info Dataset ===")
df.info()
print("\n=== Data yang digunakan ===")
df

=== Info Dataset ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75718 entries, 0 to 75717
Data columns (total 9 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Remote host                       75718 non-null  object
 1   Remote logname                    75718 non-null  object
 2   Remote user                       75718 non-null  object
 3   Request time                      75718 non-null  object
 4   Request method                    75718 non-null  object
 5   Request URI                       75718 non-null  object
 6   Request Protocol                  75718 non-null  object
 7   Status                            75718 non-null  int64
 8   Size of response (incl. headers)  75718 non-null  int64
dtypes: int64(2), object(7)
memory usage: 5.2+ MB

=== Data yang digunakan ===

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers)
0,65.55.147.227,-,-,2009-10-15T02:00:24Z,GET,/index.html,HTTP/1.1,200,21878
1,65.55.86.34,-,-,2009-10-15T02:00:58Z,GET,/index.html,HTTP/1.1,200,1416
2,148.188.55.88,-,-,2009-10-15T02:01:41Z,GET,/faq.html,HTTP/1.1,200,10946
3,66.249.139.233,-,-,2009-10-15T02:02:09Z,GET,/faq.html,HTTP/1.1,200,17247
4,72.30.50.248,-,-,2009-10-15T02:02:13Z,GET,/index.html,HTTP/1.0,200,7883
...,...,...,...,...,...,...,...,...,...
75713,65.55.251.17,-,-,2009-10-22T01:57:24Z,GET,/index.html,HTTP/1.1,200,12300
75714,67.195.151.244,-,-,2009-10-22T01:57:57Z,GET,/index.html,HTTP/1.0,200,19828
75715,65.55.178.30,-,-,2009-10-22T01:58:02Z,GET,/index.html,HTTP/1.1,200,95655
75716,67.195.176.248,-,-,2009-10-22T01:58:07Z,GET,/faq.html,HTTP/1.0,200,35002
75717,65.55.236.245,-,-,2009-10-22T01:59:33Z,GET,/index.html,HTTP/1.1,200,6695

In [11]:
if 'Request method' not in df.columns:
    raise KeyError("Kolom 'Request method' tidak ditemukan. Cek nama kolom pada df.columns")

# Filter hanya baris dengan Request method = GET
get_df = df[df['Request method'].str.upper() == 'GET']

print("\n=== 10 Baris dengan Request method = GET ===")
print(get_df.head(10))

# Hitung jumlah total baris hasil filter
print("\nJumlah total baris dengan Request method = GET:", len(get_df))

=== 10 Baris dengan Request method = GET ===
      Remote host Remote logname Remote user          Request time  \
0   65.55.147.227              -           -  2009-10-15T02:00:24Z
1     65.55.86.34              -           -  2009-10-15T02:00:58Z
2   148.188.55.88              -           -  2009-10-15T02:01:41Z
3  66.249.139.233              -           -  2009-10-15T02:02:09Z
4    72.30.50.248              -           -  2009-10-15T02:02:13Z
5     65.55.80.97              -           -  2009-10-15T02:02:51Z
6    65.55.161.41              -           -  2009-10-15T02:02:54Z
7   65.55.119.204              -           -  2009-10-15T02:02:55Z
8    65.55.58.168              -           -  2009-10-15T02:02:56Z
9     65.55.35.29              -           -  2009-10-15T02:02:55Z

  Request method  Request URI Request Protocol  Status  \
0            GET  /index.html         HTTP/1.1     200
1            GET  /index.html         HTTP/1.1     200
2            GET    /faq.html         HTTP/1.1     200
3            GET    /faq.html         HTTP/1.1     200
4            GET  /index.html         HTTP/1.0     200
5            GET  /index.html         HTTP/1.1     200
6            GET  /index.html         HTTP/1.1     200
7            GET    /faq.html         HTTP/1.1     200
8            GET  /index.html         HTTP/1.1     200
9            GET    /faq.html         HTTP/1.1     200

   Size of response (incl. headers)
0                             21878
1                              1416
2                             10946
3                             17247
4                              7883
5                              1416
6                             37122
7                             64380
8                              1202
9                            269198

Jumlah total baris dengan Request method = GET: 75656

In [12]:
# Simpan hasil ke file baru
get_df.to_csv("filtered_get_requests.csv", index=False)
print("\n✅ File hasil filter disimpan sebagai 'filtered_get_requests.csv'")

✅ File hasil filter disimpan sebagai 'filtered_get_requests.csv'

### Konversi Request Time menjadi tanggal dan waktu

In [13]:
df = pd.read_csv("filtered_get_requests.csv")

print("=== Nama Kolom ===")
df.columns

=== Nama Kolom ===

Index(['Remote host', 'Remote logname', 'Remote user', 'Request time',
       'Request method', 'Request URI', 'Request Protocol', 'Status',
       'Size of response (incl. headers)'],
      dtype='object')

In [14]:
if 'Request time' not in df.columns:
    raise KeyError("Kolom 'Request time' tidak ditemukan. Cek nama kolom pada df.columns")

# Konversi kolom 'Request time' ke format datetime
df['Request time'] = pd.to_datetime(df['Request time'], errors='coerce')

# Ubah tampilannya jadi string format 'YYYY-MM-DD HH:MM:SS'
df['Request time'] = df['Request time'].dt.strftime('%Y-%m-%d %H:%M:%S')

print("\n=== 10 Baris Pertama Setelah Konversi ===")
df[['Request time']].head(10)

=== 10 Baris Pertama Setelah Konversi ===

          Request time
0  2009-10-15 02:00:24
1  2009-10-15 02:00:58
2  2009-10-15 02:01:41
3  2009-10-15 02:02:09
4  2009-10-15 02:02:13
5  2009-10-15 02:02:51
6  2009-10-15 02:02:54
7  2009-10-15 02:02:55
8  2009-10-15 02:02:56
9  2009-10-15 02:02:55

In [15]:
# Simpan ke file baru
df.to_csv("converted_request_time.csv", index=False)
print("\n✅ Kolom 'Request time' telah dikonversi dan disimpan sebagai 'converted_request_time.csv'")

✅ Kolom 'Request time' telah dikonversi dan disimpan sebagai 'converted_request_time.csv'

### Filter Berdasarkan IP Address(Remote host) dan User Agent(Request Protocol)

In [16]:
# 1️⃣ Baca file hasil sebelumnya
df = pd.read_csv("converted_request_time.csv")

# 2️⃣ Tampilkan nama kolom untuk memastikan struktur
print("=== Nama Kolom ===")
df.columns

=== Nama Kolom ===

Index(['Remote host', 'Remote logname', 'Remote user', 'Request time',
       'Request method', 'Request URI', 'Request Protocol', 'Status',
       'Size of response (incl. headers)'],
      dtype='object')

In [17]:
required_cols = ['Remote host', 'Request Protocol']
for col in required_cols:
    if col not in df.columns:
        raise KeyError(f"Kolom '{col}' tidak ditemukan. Cek nama kolom pada df.columns")

# Tampilkan daftar unik untuk membantu memilih filter
print("\n=== Contoh Nilai Unik ===")
print("Remote host unik:", df['Remote host'].unique()[:5])
print("Request Protocol unik:", df['Request Protocol'].unique())

# Tentukan nilai filter
target_ip = '66.249.139.233'         # contoh IP
target_protocol = 'HTTP/1.1'         # contoh protokol

# Lakukan filter
filtered_df = df[
    (df['Remote host'] == target_ip) &
    (df['Request Protocol'] == target_protocol)
]

print(f"\n=== Hasil Filter untuk IP {target_ip} & Protocol {target_protocol} ===")
print(filtered_df.head(10))

# Hitung jumlah total baris hasil filter
print("\nJumlah total hasil filter:", len(filtered_df))

=== Contoh Nilai Unik ===
Remote host unik: ['65.55.147.227' '65.55.86.34' '148.188.55.88' '66.249.139.233'
 '72.30.50.248']
Request Protocol unik: ['HTTP/1.1' 'HTTP/1.0']

=== Hasil Filter untuk IP 66.249.139.233 & Protocol HTTP/1.1 ===
      Remote host Remote logname Remote user         Request time  \
3  66.249.139.233              -           -  2009-10-15 02:02:09

  Request method Request URI Request Protocol  Status  \
3            GET   /faq.html         HTTP/1.1     200

   Size of response (incl. headers)
3                             17247

Jumlah total hasil filter: 1

## Data Nasa (https://www.kaggle.com/datasets/souhagaa/nasa-access-log-dataset-1995)

### Filter Link Web HTML

In [18]:
# Muat dataset
print(f"Memuat data dari {"data.csv"}...")
df = pd.read_csv("data.csv", index_col=0)

print("\nInfo data asli:")
df.info()

print("\nData asli (head):")
df

Memuat data dari data.csv...

Info data asli:
<class 'pandas.core.frame.DataFrame'>
Index: 2965561 entries, 0 to 2965560
Data columns (total 6 columns):
 #   Column    Dtype
---  ------    -----
 0   host      object
 1   time      int64
 2   method    object
 3   url       object
 4   response  int64
 5   bytes     int64
dtypes: int64(3), object(3)
memory usage: 158.4+ MB

Data asli (head):

,host,time,method,url,response,bytes
0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,***.novo.dk,805465031,GET,/images/ksclogo-medium.gif,200,5866
2,***.novo.dk,805465051,GET,/images/MOSAIC-logosmall.gif,200,363
3,***.novo.dk,805465053,GET,/images/USA-logosmall.gif,200,234
4,***.novo.dk,805465054,GET,/images/NASA-logosmall.gif,200,786
...,...,...,...,...,...,...
2965556,zzzzzzzz.mindspring.com,809560373,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,13380
2965557,zzzzzzzz.mindspring.com,809560375,GET,/shuttle/missions/sts-69/sts-69-patch-small.gif,200,8083
2965558,zzzzzzzz.mindspring.com,809560391,GET,/images/KSC-logosmall.gif,200,1204
2965559,zzzzzzzz.mindspring.com,809560391,GET,/images/launch-logo.gif,200,1713
2965560,zzzzzzzz.mindspring.com,809560392,GET,/history/apollo/images/apollo-logo1.gif,200,1173

In [19]:
# Tentukan kolom target
# Mencari .html di kolom 'url'
target_column = "url"

if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # Filter baris
    print(f"\nMemfilter data untuk baris di mana '{target_column}' diakhiri dengan '.html'...")
    filtered_df = df[df[target_column].str.endswith('.html', na=False)].copy()

    output_filename = "html_requests_only_NASA.csv"
    filtered_df.to_csv(output_filename)

Memfilter data untuk baris di mana 'url' diakhiri dengan '.html'...

In [20]:
print(f"\nBerhasil memfilter data dan menyimpannya ke {output_filename}.")
print("Pratinjau data yang telah difilter:")
filtered_df

Berhasil memfilter data dan menyimpannya ke html_requests_only_NASA.csv.
Pratinjau data yang telah difilter:

,host,time,method,url,response,bytes
0,***.novo.dk,805465029,GET,/ksc.html,200,7067
6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200,8678
12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200,6922
13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,11264
23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200,4665
...,...,...,...,...,...,...
2965543,zzz.pe.u-tokyo.ac.jp,805633446,GET,/shuttle/technology/sts-newsref/sts-lcc.html,200,32252
2965546,zzz.pe.u-tokyo.ac.jp,805633480,GET,/shuttle/missions/sts-70/movies/movies.html,200,1395
2965551,zzz.pe.u-tokyo.ac.jp,805634091,GET,/shuttle/missions/sts-70/images/images.html,200,4048
2965553,zzz.pe.u-tokyo.ac.jp,805634266,GET,/shuttle/resources/orbiters/discovery.html,200,6861
2965556,zzzzzzzz.mindspring.com,809560373,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,13380

### Filter status mengambil nilai yg 200

In [21]:
# Muat dataset
print(f"Memuat data dari {"html_requests_only_NASA.csv"}...")
df = pd.read_csv("html_requests_only_NASA.csv")

Memuat data dari html_requests_only_NASA.csv...

In [22]:
# Tentukan kolom target
target_column = "response"

if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    if pd.api.types.is_numeric_dtype(df[target_column]):

        # Filter baris di mana 'response' sama dengan 200
        print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah 200...")
        filtered_df = df[df[target_column] == 200].copy()

        output_filename = "status_200_only_NASA.csv"
        filtered_df.to_csv(output_filename, index=False)
    else:
        print(f"Error: Kolom '{target_column}' bukan numerik")

Memfilter data untuk baris di mana 'response' adalah 200...

In [23]:
print(f"\nBerhasil memfilter data dan menyimpannya ke {output_filename}.")
print("Pratinjau data yang telah difilter:")
filtered_df

Berhasil memfilter data dan menyimpannya ke status_200_only_NASA.csv.
Pratinjau data yang telah difilter:

,Unnamed: 0,host,time,method,url,response,bytes
0,0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200,8678
2,12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200,6922
3,13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,11264
4,23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200,4665
...,...,...,...,...,...,...,...
643512,2965543,zzz.pe.u-tokyo.ac.jp,805633446,GET,/shuttle/technology/sts-newsref/sts-lcc.html,200,32252
643513,2965546,zzz.pe.u-tokyo.ac.jp,805633480,GET,/shuttle/missions/sts-70/movies/movies.html,200,1395
643514,2965551,zzz.pe.u-tokyo.ac.jp,805634091,GET,/shuttle/missions/sts-70/images/images.html,200,4048
643515,2965553,zzz.pe.u-tokyo.ac.jp,805634266,GET,/shuttle/resources/orbiters/discovery.html,200,6861
643516,2965556,zzzzzzzz.mindspring.com,809560373,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,13380

### Filter Request Method mengambil yg GET

In [24]:
filter_value = "GET"
target_column = "method"

# Muat dataset
print(f"Memuat data dari {"status_200_only_NASA.csv"}...")
df = pd.read_csv("status_200_only_NASA.csv")

Memuat data dari status_200_only_NASA.csv...

In [25]:
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah '{filter_value}'...")
    filtered_df = df[df[target_column] == filter_value].copy()

    output_filename = "method_get_only_NASA.csv"
    filtered_df.to_csv(output_filename, index=False)

Memfilter data untuk baris di mana 'method' adalah 'GET'...

In [26]:
print(f"\nBerhasil memfilter data dan menyimpannya ke {output_filename}.")
print("Pratinjau data yang telah difilter:")
filtered_df

Berhasil memfilter data dan menyimpannya ke method_get_only_NASA.csv.
Pratinjau data yang telah difilter:

,Unnamed: 0,host,time,method,url,response,bytes
0,0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200,8678
2,12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200,6922
3,13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,11264
4,23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200,4665
...,...,...,...,...,...,...,...
610979,2965543,zzz.pe.u-tokyo.ac.jp,805633446,GET,/shuttle/technology/sts-newsref/sts-lcc.html,200,32252
610980,2965546,zzz.pe.u-tokyo.ac.jp,805633480,GET,/shuttle/missions/sts-70/movies/movies.html,200,1395
610981,2965551,zzz.pe.u-tokyo.ac.jp,805634091,GET,/shuttle/missions/sts-70/images/images.html,200,4048
610982,2965553,zzz.pe.u-tokyo.ac.jp,805634266,GET,/shuttle/resources/orbiters/discovery.html,200,6861
610983,2965556,zzzzzzzz.mindspring.com,809560373,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,13380

### Konversi Request Time menjadi tanggal dan waktu

In [27]:
target_column = "time"

# Muat dataset
print(f"Memuat data dari {"method_get_only_NASA.csv"}...")
df = pd.read_csv("method_get_only_NASA.csv")

Memuat data dari method_get_only_NASA.csv...

In [28]:
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    print(f"Format asli (baris pertama): {df[target_column].iloc[0]}")
    print(f"Mengonversi kolom '{target_column}' (Unix timestamp) ke format Datetime...")

    df['datetime_readable'] = pd.to_datetime(df[target_column], unit='s')

    output_filename = "time_converted_NASA.csv"
    df.to_csv(output_filename, index=False)

Format asli (baris pertama): 805465029
Mengonversi kolom 'time' (Unix timestamp) ke format Datetime...

In [29]:
print(f"\nBerhasil mengonversi data waktu dan menyimpannya ke {output_filename}.")
print("Pratinjau data yang telah diubah:")
df

Berhasil mengonversi data waktu dan menyimpannya ke time_converted_NASA.csv.
Pratinjau data yang telah diubah:

,Unnamed: 0,host,time,method,url,response,bytes,datetime_readable
0,0,***.novo.dk,805465029,GET,/ksc.html,200,7067,1995-07-11 12:17:09
1,6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200,8678,1995-07-11 12:17:48
2,12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200,6922,1995-07-11 12:23:01
3,13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,11264,1995-08-09 07:02:48
4,23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200,4665,1995-08-09 07:05:38
...,...,...,...,...,...,...,...,...
608911,2965543,zzz.pe.u-tokyo.ac.jp,805633446,GET,/shuttle/technology/sts-newsref/sts-lcc.html,200,32252,1995-07-13 11:04:06
608912,2965546,zzz.pe.u-tokyo.ac.jp,805633480,GET,/shuttle/missions/sts-70/movies/movies.html,200,1395,1995-07-13 11:04:40
608913,2965551,zzz.pe.u-tokyo.ac.jp,805634091,GET,/shuttle/missions/sts-70/images/images.html,200,4048,1995-07-13 11:14:51
608914,2965553,zzz.pe.u-tokyo.ac.jp,805634266,GET,/shuttle/resources/orbiters/discovery.html,200,6861,1995-07-13 11:17:46
608915,2965556,zzzzzzzz.mindspring.com,809560373,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,13380,1995-08-27 21:52:53

### Filter Berdasarkan IP Address(Remote host) dan User Agent(Request Protocol)

In [30]:
file_name = "time_converted_NASA.csv"

col_ip = "host"               # Kolom untuk mengelompokkan sesi
col_time = "datetime_readable" # Kolom untuk mengurutkan sesi
new_col_name = "SESSION"      # Nama kolom sesi baru

print(f"Memuat data dari {file_name}...")
try:
    df = pd.read_csv(file_name, parse_dates=[col_time])
except FileNotFoundError:
    print(f"Error: File {file_name} tidak ditemukan.")
    print("Pastikan Anda sudah menjalankan skrip konversi 'time' sebelumnya.")
    exit()
except ValueError as e:
    print(f"Error saat membaca {file_name}. Cek kolom '{col_time}'.")
    print(f"Detail: {e}")
    exit()

Memuat data dari time_converted_NASA.csv...

In [31]:
if col_ip in df.columns and col_time in df.columns:
    print(f"Membuat kolom '{new_col_name}' berdasarkan '{col_ip}' unik...")
    df[new_col_name] = df[col_ip].astype('category').cat.codes + 1

    # Urutkan data berdasarkan SESSION, lalu WAKTU
    print(f"Mengurutkan data berdasarkan '{new_col_name}' dan '{col_time}'...")
    df_sorted = df.sort_values(by=[new_col_name, col_time], ascending=True)

    # Hapus kolom 'time' (timestamp angka) yang asli
    if 'time' in df_sorted.columns:
        print("Menghapus kolom 'time' (timestamp unix) asli...")
        df_sorted = df_sorted.drop(columns=['time'])

    output_filename = "session_data_full_NASA.csv"
    df_sorted.to_csv(output_filename, index=False)
else:
    print(f"Error: Kolom '{col_ip}' atau '{col_time}' tidak ditemukan di {file_name}.")

Membuat kolom 'SESSION' berdasarkan 'host' unik...
Mengurutkan data berdasarkan 'SESSION' dan 'datetime_readable'...
Menghapus kolom 'time' (timestamp unix) asli...

In [32]:
print(f"\nBerhasil! Kolom '{new_col_name}' telah ditambahkan.")
print(f"File baru disimpan sebagai: {output_filename}")
print("\nPratinjau data baru:")

preview_cols = [new_col_name, col_ip, col_time, 'url']
df_sorted[preview_cols]

Berhasil! Kolom 'SESSION' telah ditambahkan.
File baru disimpan sebagai: session_data_full_NASA.csv

Pratinjau data baru:

,SESSION,host,datetime_readable,url
0,1,***.novo.dk,1995-07-11 12:17:09,/ksc.html
1,1,***.novo.dk,1995-07-11 12:17:48,/shuttle/missions/missions.html
2,1,***.novo.dk,1995-07-11 12:23:01,/shuttle/resources/orbiters/columbia.html
3,1,***.novo.dk,1995-08-09 07:02:48,/shuttle/missions/sts-69/mission-sts-69.html
4,1,***.novo.dk,1995-08-09 07:05:38,/shuttle/countdown/liftoff.html
...,...,...,...,...
608911,113440,zzz.pe.u-tokyo.ac.jp,1995-07-13 11:04:06,/shuttle/technology/sts-newsref/sts-lcc.html
608912,113440,zzz.pe.u-tokyo.ac.jp,1995-07-13 11:04:40,/shuttle/missions/sts-70/movies/movies.html
608913,113440,zzz.pe.u-tokyo.ac.jp,1995-07-13 11:14:51,/shuttle/missions/sts-70/images/images.html
608914,113440,zzz.pe.u-tokyo.ac.jp,1995-07-13 11:17:46,/shuttle/resources/orbiters/discovery.html
608915,113441,zzzzzzzz.mindspring.com,1995-08-27 21:52:53,/shuttle/missions/sts-69/mission-sts-69.html